### ISSUE TITLE
nonce mode

### ISSUE THREAD

**Issue by LucidOne** [ulid/spec#18]
Given [recent](https://en.wikipedia.org/wiki/Meltdown_(security_vulnerability)) [events](https://en.wikipedia.org/wiki/Spectre_(security_vulnerability)) I'd like to avoid leaking high resolution clock data.

Perhaps the ULID spec could offer support for some sort of nonce offset.

**Comment by RobThree** [comment]
The resolution of the timestamp in a ULID is millisecond resolution. That's nowhere near 'high resolution' nor is it useful for timing attack sidechannels (which is what you are, basically, worried about).
