### ISSUE TITLE
[Q] shortenning to 20 characters

### ISSUE THREAD

**Issue by vladp** [ulid/spec#35]
our payment processor requires 20 character long reference ID.
We are already using ULID for our order IDs, so I would like to just chop off the first 6 characters
to get it from 26 to 20.

We do not need ids to be crypto-secure.
Just something that's reasonably unique within 10 mln entries space

Would that work?

**Comment by mqudsi** [comment]
That cuts the most significant bits of the timestamp and breaks sort, bad idea.

Keep the first ten characters (timestamp), skip six characters (randomness), and keep the rest. That'll preserve the millisecond conflict resolution.

**Comment by vladp** [comment]
@mqudsi   thank you very much for the follow up.

With your suggestion, would I then trade uniqueness probability (eg make it slightly less unique) for sort-ability ?
I also assumed that the random part is sort-able on its own, but clearly I was mistaken.

**Comment by alizain** [comment]
As @mqudsi  said, don't chop off the first 6 characters, you'll break ULID quite badly.

By removing the last 6 characters, you're reducing your entropy from 2 ^ 80 to 2 ^ 50 within the same millisecond. Depending on your use-case, that may still work.

**Comment by vladp** [comment]
Thank you @mqudsi  @alizain. Will implement your suggestion.
