### ISSUE TITLE
Clarification of Crockford Base32

### ISSUE THREAD

**Issue by tuupola** [ulid/spec#38]
The spec says:

_"Uses Crockford's base32 for better efficiency and readability (5 bits per character)"_

_"Crockford's Base32 is used as shown. This alphabet excludes the letters I, L, O, and U to avoid confusion and abuse."_

However it is not exactly clear does this mean only using the character set `0123456789ABCDEFGHJKMNPQRSTVWXYZ` or does it mean using also the Crockford base32 features such as treating `i` and `l` as `1`, treating `o` as `0` and ignoring hyphens in the string?

**Comment by tuupola** [comment]
Ping @alizain

**Comment by alizain** [comment]
This part of the spec can be better written. The reference JS implementation does not use the other Crockford base32 features, it only uses the reduced character set.
