### ISSUE TITLE
[Question]: Are ULIDs globally unique and appropriate for a high volume chat app?

### ISSUE THREAD

**Issue by codinronan** [ulid/spec#54]
I apologize if this isn't the place to ask this --

Specifically my scenario would be to use the Javascript ULID library inside AWS lambdas, which are processing the incoming messages and assigning them IDs which are then partitioned in Dynamo (for which ULID is an ideal structure).

This is a scenario where several lambdas may be receiving messages in the same moment. Will these generate unique globally unique ULIDs?

**Comment by RobThree** [comment]
Yes. Have you read the spec?

**Comment by codinronan** [comment]
Yes. It talks about within a single machine, or rather, doesn't explicitly say that among different machines, ULIDs generated in the same millisecond will be globally unique (the phrase 'globally unique' doesn't appear). Thus the question.

I realize it might be a bit pedantic, I just wanted to verify..

**Comment by RobThree** [comment]
A ULID has 80 bits of randomness so, for **_most_** intents and purposes, you should be fine. You should ask yourself why you're choosing, or considering, a ULID over a (G/U)UID (for example <sub>or maybe an auto-incrementing ID</sub>) in the first place. Once you can answer that question for yourself you should also be able to answer if the 80 random bits are "(globally) unique" _enough_ for you. The chance of a collision for both a [(G/U)UID](https://www.google.com/search?q=.5+%2B+sqrt(.25+%2B+2*ln(2)+*+2%5E122)) and [ULID](https://www.google.com/search?q=.5+%2B+sqrt(.25+%2B+2*ln(2)+*+2%5E80)) differ by several orders of magnitude but are still very, very small in both cases.

**Comment by codinronan** [comment]
Hey @RobThree thanks so much for answering. Ok, that should be sufficient. The reason I'm considering it are:

* It's for a chat application for storing message ID's, so sufficient randomness + uniqueness is important
* For various reasons we've chosen to use Dynamo DB
* Auto-incrementing ID's are hard to synchronize across webservices that may create them
* ULID's are ideally suited to the way Dynamo uses sort keys and pre-indexing
